apiVersion: v1
kind: Service
metadata:
  name: game-svc
  namespace: keycloak
  labels:
    app: game-app
spec:
  selector:
    app: game-app
  type: {{ .Values.game.service.type }}
  ports:
    - name: http
      port: {{ .Values.game.service.port }}
      targetPort: {{ .Values.game.service.targetPort }}