apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.ingress.keycloakServicePort }}
          - path: {{ .Values.ingress.gamePath }}
            pathType: Prefix
            backend:
              service:
                name: game-svc
                port:
                  number: {{ .Values.ingress.gameServicePort }}
          - path: {{ .Values.ingress.loginPath }}
            pathType: Prefix
            backend:
              service:
                name: game-svc
                port:
                  number: {{ .Values.ingress.gameServicePort }}
          - path: {{ .Values.ingress.authPath }}
            pathType: Prefix
            backend:
              service:
                name: game-svc
                port:
                  number: {{ .Values.ingress.gameServicePort }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}