# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: keycloak
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.dbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.dbPassword | b64enc}}
