apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: keycloak
type: Opaque
data:
  client-secret: {{ .Values.secrets.client.secret | b64enc }}
  client-id: {{ .Values.secrets.client.id | b64enc }}
  database_user: {{ .Values.postgres.dbUser | b64enc }}
  database_password: {{ .Values.postgres.dbPassword | b64enc}}
